---
# tasks file for haproxy


- name: Install haproxy packages
  apt: pkg={{ item }} state=present
  with_items:
  -  haproxy
  tags: [ haproxy, packages ]

- name: enable haproxy service
  service: name=haproxy.service enabled=yes
  tags: [ haproxy ]

- name: haproxy kernel tuning
  sysctl: name={{ item.name }} value="{{ item.value }}" sysctl_file="/etc/sysctl.d/90-haproxy-ipv4.conf" state=present
  tags: [haproxy, sysctl]
  with_items:
    - { name: net.ipv4.tcp_congestion_control, value: 'htcp'}
    - { name: net.ipv4.tcp_fin_timeout, value: 10}
    - { name: net.ipv4.tcp_sack, value: 1}
    - { name: net.ipv4.tcp_window_scaling, value: 1}
    - { name: net.ipv4.tcp_max_tw_buckets, value: 8192}
    - { name: net.ipv4.tcp_timestamps, value: 1}
    - { name: net.ipv4.ip_nonlocal_bind, value: 1}
    - { name: net.ipv4.tcp_syncookies, value: 1}
    - { name: net.ipv4.conf.all.rp_filter, value: 0}
    - { name: net.ipv4.tcp_max_syn_backlog, value: 1024}
    - { name: net.ipv4.ip_local_port_range, value: '1024 63999' }

- name: haproxy kernel tuning
  sysctl: name={{ item.name }} value="{{ item.value }}" sysctl_file="/etc/sysctl.d/90-haproxy-ipv6.conf" state=present
  tags: [haproxy, sysctl]
  with_items:
    - { name: net.ipv6.ip_nonlocal_bind, value: 1}

- name: make /etc/ssl/private/haproxy/
  file: path="/etc/ssl/private/haproxy/" mode=0700 state=directory owner=root
  tags: [haproxy]


- name: add haproxy config
  template: src="{{ haproxy_config }}" dest="/etc/haproxy/haproxy.cfg"
  notify:
    - reload haproxy
  tags: [haproxy, haproxy-cfg]


