- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-minimal

- hosts: all
  gather_facts: yes
  become: yes
  roles:
  - { role: common }
- hosts: nginx
  become: yes
  roles:
  - { role: nginx }
  - { role: uwsgi-app }
- hosts: haproxy
  become: yes
  roles:
  - { role: haproxy }

